//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alita
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlitaDatabase : DbContext
    {
        public AlitaDatabase()
            : base("name=AlitaDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agv> Agv { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<ErrorReport> ErrorReport { get; set; }
        public virtual DbSet<ExternalDevice> ExternalDevice { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Platform> Platform { get; set; }
        public virtual DbSet<RobotServer> RobotServer { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
    }
}
