//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alita
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agv()
        {
            this.ErrorReport = new HashSet<ErrorReport>();
            this.Job = new HashSet<Job>();
        }
    
        public long Id { get; set; }
        public System.DateTime WasBought { get; set; }
        public string NameOnServer { get; set; }
        public string Owner { get; set; }
        public Nullable<long> Platform_Id { get; set; }
        public Nullable<long> Device_Id { get; set; }
        public Nullable<long> ServerId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual RobotServer RobotServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorReport> ErrorReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Job { get; set; }
    }
}
