//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alita
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorReport
    {
        public long Id { get; set; }
        public System.DateTime WhenHappend { get; set; }
        public bool EstopPressed { get; set; }
        public long PositionX { get; set; }
        public long PositionY { get; set; }
        public int Heading { get; set; }
        public string Log { get; set; }
        public Nullable<long> AGV_FK { get; set; }
    
        public virtual Agv Agv { get; set; }
    }
}
