//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alita
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalDevice
    {
        public long Id { get; set; }
        public string Comment { get; set; }
        public Nullable<long> Location_FK { get; set; }
        public Nullable<long> Device_Id { get; set; }
        public string Callname { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Location Location { get; set; }
    }
}
