//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alita
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public long Id { get; set; }
        public string IdOnServer { get; set; }
        public string SourceGoal { get; set; }
        public string TargetGoal { get; set; }
        public System.DateTime Queued { get; set; }
        public Nullable<System.DateTime> Finnished { get; set; }
        public long Server_Id { get; set; }
        public Nullable<long> Agv_Id { get; set; }
    
        public virtual Agv Agv { get; set; }
        public virtual RobotServer RobotServer { get; set; }
    }
}
